export const UPLOAD_IMAGE_REQUEST_SEND = "UPLOAD_IMAGE_REQUEST_SEND";
export const UPLOAD_IMAGE_REQUEST_SUCCESS = "UPLOAD_IMAGE_REQUEST_SUCCESS";
export const UPLOAD_IMAGE_REQUEST_FAIL = "UPLOAD_IMAGE_REQUEST_FAIL";
export const SELECT_IMAGE = "SELECT_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const SELECT_FOLDER = "SELECT_FOLDER";
export const ADD_LIST_FOLDER = "ADD_LIST_FOLDER";
export const IMAGE_SELECTION_ERROR = "IMAGE_SELECTION_ERROR";
export const UPLOAD_IMAGE_DONE = "UPLOAD_IMAGE_DONE";

export const IMAGE_GALLEY_MARK_SELECT = "IMAGE_GALLEY_MARK_SELECT";
export const IMAGE_GALLEY_MARK_REMOVE = "IMAGE_GALLEY_MARK_REMOVE";
export const IMAGE_GALLEY_MARK_REMOVE_ALL = "IMAGE_GALLEY_MARK_REMOVE_ALL";

export const IMAGE_GALLEY_LIST_REQUEST_SEND = "IMAGE_GALLEY_LIST_REQUEST_SEND";
export const IMAGE_GALLEY_LIST_REQUEST_SUCCESS =
  "IMAGE_GALLEY_LIST_REQUEST_SUCCESS";
export const IMAGE_GALLEY_LIST_REQUEST_FAIL = "IMAGE_GALLEY_LIST_REQUEST_FAIL";

export const IMAGE_FOLDER_LIST_REQUEST_SEND = "IMAGE_FOLDER_REQUEST_SEND";
export const IMAGE_FOLDER_LIST_REQUEST_SUCCESS = "IMAGE_FOLDER_REQUEST_SUCCESS";
export const IMAGE_FOLDER_LIST_REQUEST_FAIL = "IMAGE_FOLDER_REQUEST_FAIL";
export const IMAGE_FOLDER_LIST_ADD = "IMAGE_FOLDER_LIST_ADD";

export const IMAGE_FOLDER_ADD_REQUEST_SEND = "IMAGE_FOLDER_ADD_REQUEST_SEND";
export const IMAGE_FOLDER_ADD_REQUEST_SUCCESS =
  "IMAGE_FOLDER_ADD_REQUEST_SUCCESS";
export const IMAGE_FOLDER_ADD_REQUEST_FAIL = "IMAGE_FOLDER_ADD_REQUEST_FAIL";

//banner
export const BANNER_REQUEST_SEND = "BANNER_REQUEST_SEND";
export const BANNER_REQUEST_SUCCESS = "BANNER_REQUEST_SUCCESS";
export const BANNER_REQUEST_FAIL = "BANNER_REQUEST_FAIL";
export const BANNER_REQUEST_ADD = "BANNER_REQUEST_ADD";
export const OPEN_EDIT_PAGE = "OPEN_EDIT_PAGE";

export const BANNER_ADD_REQUEST_SENT = "BANNER_ADD_REQUEST_SENT";
export const BANNER_ADD_REQUEST_FAIL = "BANNER_ADD_REQUEST_FAIL";
export const BANNER_ADD_REQUEST_SUCCESS = "BANNER_ADD_REQUEST_SUCCESS";
export const BANNER_MESSAGE_CLEAR = "BANNER_MESSAGE_CLEAR";
export const BANNER_FILTER_SELECT = "BANNER_FILTER_SELECT";

export const EDIT_BANNER_REQUEST_SEND = "EDIT_BANNER_REQUEST_SEND";
export const EDIT_BANNER_REQUEST_SUCCESS = "EDIT_BANNER_REQUEST_SUCCESS";
export const GET_EDITED_BANNER = "GET_EDITED_BANNER";
export const EDIT_BANNER_REQUEST_FAIL = "EDIT_BANNER_REQUEST_FAIL";

export const DELETE_BANNER_REQUEST_SEND = "DELETE_BANNER_REQUEST_SEND";
export const DELETE_BANNER_REQUEST_SUCCESS = "DELETE_BANNER_REQUEST_SUCCESS";
export const DELETE_BANNER_REQUEST_FAIL = "DELETE_BANNER_REQUEST_FAIL";






// ADMIN ROLE

export const CREATE_ADMIN_ROLE_REQUEST_SEND = "CREATE_ADMIN_ROLE_REQUEST_SEND";
export const CREATE_ADMIN_ROLE_REQUEST_SUCCESS =
  "CREATE_ADMIN_ROLE_REQUEST_SUCCESS";
export const CREATE_ADMIN_ROLE_REQUEST_FAIL = "CREATE_ADMIN_ROLE_REQUEST_FAIL";
export const GET_CREATED_ADMIN_ROLE = "GET_CREATED_ADMIN_ROLE";

export const GET_ALL_ROLE_REQUEST_SEND = "GET_ALL_ROLE_REQUEST_SEND";
export const GET_ALL_ROLE_REQUEST_SUCCESS = "GET_ALL_ROLE_REQUEST_SUCCESS";
export const GET_ALL_ROLE_REQUEST_FAIL = "GET_ALL_ROLE_REQUEST_FAIL";

export const EDIT_ADMIN_ROLE_REQUEST_SEND = "EDIT_ADMIN_ROLE_REQUEST_SEND";
export const EDIT_ADMIN_ROLE_REQUEST_SUCCESS =
  "EDIT_ADMIN_ROLE_REQUEST_SUCCESS";
export const EDIT_ADMIN_ROLE_REQUEST_FAIL = "EDIT_ADMIN_ROLE_REQUEST_FAIL";
export const GET_UPDATE_ADMIN_ROLE = "GET_UPDATE_ADMIN_ROLE";

export const DELETE_ROLE_REQUEST_SEND = "DELETE_ROLE_REQUEST_SEND";
export const DELETE_ROLE_REQUEST_SUCCESS = "DELETE_ROLE_REQUEST_SUCCESS";
export const DELETE_ROLE_REQUEST_FAIL = "DELETE_ROLE_REQUEST_FAIL";

export const RESTORE_ROLE_REQUEST_SEND = "RESTORE_ROLE_REQUEST_SEND";
export const RESTORE_ROLE_REQUEST_SUCCESS = "RESTORE_ROLE_REQUEST_SUCCESS";
export const RESTORE_ROLE_REQUEST_FAIL = "RESTORE_ROLE_REQUEST_FAIL";



// USERS

export const GET_ALL_USERS_REQUEST_SEND = "GET_ALL_USERS_REQUEST_SEND";
export const GET_ALL_USERS_REQUEST_SUCCESS = "GET_ALL_USERS_REQUEST_SUCCESS";
export const GET_ALL_USERS_REQUEST_FAIL = "GET_ALL_USERS_REQUEST_FAIL";

export const ADD_USER_REQUEST_SEND = "ADD_USER_REQUEST_SEND";
export const ADD_USER_REQUEST_SUCCESS = "ADD_USER_REQUEST_SUCCESS";
export const ADD_USER_REQUEST_FAIL = "ADD_USER_REQUEST_FAIL";

export const EDIT_USER_REQUEST_SEND = "EDIT_USER_REQUEST_SEND";
export const EDIT_USER_REQUEST_SUCCESS = "EDIT_USER_REQUEST_SUCCESS";
export const EDIT_USER_REQUEST_FAIL = "EDIT_USER_REQUEST_FAIL";

export const UPDATE_USERS_STATUS_KEY = "UPDATE_USERS_STATUS_KEY";
export const UPDATE_USERS_SEARCH_KEY = "UPDATE_USERS_SEARCH_KEY";
export const UPDATE_USERS_CREATED_BY_KEY = "UPDATE_USERS_CREATED_BY_KEY";

// FILTER KEY

export const UPDATE_SEARCH_KEY = "UPDATE_SEARCH_KEY";
export const UPDATE_STATUS_KEY = "UPDATE_STATUS_KEY";
export const UPDATE_CREATED_BY_KEY = "UPDATE_CREATED_BY_KEY";
export const UPDATE_CURRENT_STATUS_KEY = "UPDATE_CURRENT_STATUS_KEY";
// export const SET_STATUS_FALSE = "SET_STATUS_FALSE";








