export const UPLOAD_IMAGE_REQUEST_SEND = "UPLOAD_IMAGE_REQUEST_SEND";
export const UPLOAD_IMAGE_REQUEST_SUCCESS = "UPLOAD_IMAGE_REQUEST_SUCCESS";
export const UPLOAD_IMAGE_REQUEST_FAIL = "UPLOAD_IMAGE_REQUEST_FAIL";
export const SELECT_IMAGE = "SELECT_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const SELECT_FOLDER = "SELECT_FOLDER";
export const ADD_LIST_FOLDER = "ADD_LIST_FOLDER";
export const IMAGE_SELECTION_ERROR = "IMAGE_SELECTION_ERROR";
export const UPLOAD_IMAGE_DONE = "UPLOAD_IMAGE_DONE";

export const IMAGE_GALLEY_MARK_SELECT = "IMAGE_GALLEY_MARK_SELECT";
export const IMAGE_GALLEY_MARK_REMOVE = "IMAGE_GALLEY_MARK_REMOVE";
export const IMAGE_GALLEY_MARK_REMOVE_ALL = "IMAGE_GALLEY_MARK_REMOVE_ALL";

export const IMAGE_GALLEY_LIST_REQUEST_SEND = "IMAGE_GALLEY_LIST_REQUEST_SEND";
export const IMAGE_GALLEY_LIST_REQUEST_SUCCESS =
  "IMAGE_GALLEY_LIST_REQUEST_SUCCESS";
export const IMAGE_GALLEY_LIST_REQUEST_FAIL = "IMAGE_GALLEY_LIST_REQUEST_FAIL";

export const IMAGE_FOLDER_LIST_REQUEST_SEND = "IMAGE_FOLDER_REQUEST_SEND";
export const IMAGE_FOLDER_LIST_REQUEST_SUCCESS = "IMAGE_FOLDER_REQUEST_SUCCESS";
export const IMAGE_FOLDER_LIST_REQUEST_FAIL = "IMAGE_FOLDER_REQUEST_FAIL";
export const IMAGE_FOLDER_LIST_ADD = "IMAGE_FOLDER_LIST_ADD";

export const IMAGE_FOLDER_ADD_REQUEST_SEND = "IMAGE_FOLDER_ADD_REQUEST_SEND";
export const IMAGE_FOLDER_ADD_REQUEST_SUCCESS =
  "IMAGE_FOLDER_ADD_REQUEST_SUCCESS";
export const IMAGE_FOLDER_ADD_REQUEST_FAIL = "IMAGE_FOLDER_ADD_REQUEST_FAIL";

//banner
export const BANNER_REQUEST_SEND = "BANNER_REQUEST_SEND";
export const BANNER_REQUEST_SUCCESS = "BANNER_REQUEST_SUCCESS";
export const BANNER_REQUEST_FAIL = "BANNER_REQUEST_FAIL";
export const BANNER_REQUEST_ADD = "BANNER_REQUEST_ADD";
export const OPEN_EDIT_PAGE = "OPEN_EDIT_PAGE";

export const BANNER_ADD_REQUEST_SENT = "BANNER_ADD_REQUEST_SENT";
export const BANNER_ADD_REQUEST_FAIL = "BANNER_ADD_REQUEST_FAIL";
export const BANNER_ADD_REQUEST_SUCCESS = "BANNER_ADD_REQUEST_SUCCESS";
export const BANNER_MESSAGE_CLEAR = "BANNER_MESSAGE_CLEAR";
export const BANNER_FILTER_SELECT = "BANNER_FILTER_SELECT";

export const EDIT_BANNER_REQUEST_SEND = "EDIT_BANNER_REQUEST_SEND";
export const EDIT_BANNER_REQUEST_SUCCESS = "EDIT_BANNER_REQUEST_SUCCESS";
export const GET_EDITED_BANNER = "GET_EDITED_BANNER";
export const EDIT_BANNER_REQUEST_FAIL = "EDIT_BANNER_REQUEST_FAIL";

export const DELETE_BANNER_REQUEST_SEND = "DELETE_BANNER_REQUEST_SEND";
export const DELETE_BANNER_REQUEST_SUCCESS = "DELETE_BANNER_REQUEST_SUCCESS";
export const DELETE_BANNER_REQUEST_FAIL = "DELETE_BANNER_REQUEST_FAIL";



// ADMIN 

export const ADD_ADMIN_REQUEST_SEND = "ADD_ADMIN_REQUEST_SEND";
export const ADD_ADMIN_REQUEST_SUCCESS = "ADD_ADMIN_REQUEST_SUCCESS";
export const ADD_ADMIN_REQUEST_FAIL = "ADD_ADMIN_REQUEST_FAIL";

export const GET_ALL_ADMIN_REQUEST_SEND = "GET_ALL_ADMIN_REQUEST_SEND";
export const GET_ALL_ADMIN_REQUEST_SUCCESS = "GET_ALL_ADMIN_REQUEST_SUCCESS";
export const GET_ALL_ADMIN_REQUEST_FAIL = "GET_ALL_ADMIN_REQUEST_FAIL";

export const DELETE_ADMIN_REQUEST_SEND = "DELETE_ADMIN_REQUEST_SEND";
export const DELETE_ADMIN_REQUEST_SUCCESS = "DELETE_ADMIN_REQUEST_SUCCESS";
export const DELETE_ADMIN_REQUEST_FAIL = "DELETE_ADMIN_REQUEST_FAIL";

export const EDIT_ADMIN_REQUEST_SEND = "EDIT_ADMIN_REQUEST_SEND";
export const EDIT_ADMIN_REQUEST_SUCCESS = "EDIT_ADMIN_REQUEST_SUCCESS";
export const EDIT_ADMIN_REQUEST_FAIL = "EDIT_ADMIN_REQUEST_FAIL";

// ROLE

export const CREATE_ADMIN_ROLE_REQUEST_SEND = "CREATE_ADMIN_ROLE_REQUEST_SEND";
export const CREATE_ADMIN_ROLE_REQUEST_SUCCESS =
  "CREATE_ADMIN_ROLE_REQUEST_SUCCESS";
export const CREATE_ADMIN_ROLE_REQUEST_FAIL = "CREATE_ADMIN_ROLE_REQUEST_FAIL";
export const GET_CREATED_ADMIN_ROLE = "GET_CREATED_ADMIN_ROLE";

export const GET_ALL_ROLE_REQUEST_SEND = "GET_ALL_ROLE_REQUEST_SEND";
export const GET_ALL_ROLE_REQUEST_SUCCESS = "GET_ALL_ROLE_REQUEST_SUCCESS";
export const GET_ALL_ROLE_REQUEST_FAIL = "GET_ALL_ROLE_REQUEST_FAIL";

export const EDIT_ADMIN_ROLE_REQUEST_SEND = "EDIT_ADMIN_ROLE_REQUEST_SEND";
export const EDIT_ADMIN_ROLE_REQUEST_SUCCESS =
  "EDIT_ADMIN_ROLE_REQUEST_SUCCESS";
export const EDIT_ADMIN_ROLE_REQUEST_FAIL = "EDIT_ADMIN_ROLE_REQUEST_FAIL";
export const GET_UPDATE_ADMIN_ROLE = "GET_UPDATE_ADMIN_ROLE";

export const DELETE_ROLE_REQUEST_SEND = "DELETE_ROLE_REQUEST_SEND";
export const DELETE_ROLE_REQUEST_SUCCESS = "DELETE_ROLE_REQUEST_SUCCESS";
export const DELETE_ROLE_REQUEST_FAIL = "DELETE_ROLE_REQUEST_FAIL";

export const RESTORE_ROLE_REQUEST_SEND = "RESTORE_ROLE_REQUEST_SEND";
export const RESTORE_ROLE_REQUEST_SUCCESS = "RESTORE_ROLE_REQUEST_SUCCESS";
export const RESTORE_ROLE_REQUEST_FAIL = "RESTORE_ROLE_REQUEST_FAIL";



// USERS

export const GET_ALL_USERS_REQUEST_SEND = "GET_ALL_USERS_REQUEST_SEND";
export const GET_ALL_USERS_REQUEST_SUCCESS = "GET_ALL_USERS_REQUEST_SUCCESS";
export const GET_ALL_USERS_REQUEST_FAIL = "GET_ALL_USERS_REQUEST_FAIL";

export const ADD_USER_REQUEST_SEND = "ADD_USER_REQUEST_SEND";
export const ADD_USER_REQUEST_SUCCESS = "ADD_USER_REQUEST_SUCCESS";
export const ADD_USER_REQUEST_FAIL = "ADD_USER_REQUEST_FAIL";

export const EDIT_USER_REQUEST_SEND = "EDIT_USER_REQUEST_SEND";
export const EDIT_USER_REQUEST_SUCCESS = "EDIT_USER_REQUEST_SUCCESS";
export const EDIT_USER_REQUEST_FAIL = "EDIT_USER_REQUEST_FAIL";

export const UPDATE_USERS_SORT_KEY = "UPDATE_USERS_SORT_KEY";
export const UPDATE_USERS_SEARCH_KEY = "UPDATE_USERS_SEARCH_KEY";

// CATEGORY 

export const ADD_CATEGORY_REQUEST_SEND = "ADD_CATEGORY_REQUEST_SEND";
export const ADD_CATEGORY_REQUEST_SUCCESS = "ADD_CATEGORY_REQUEST_SUCCESS";
export const ADD_CATEGORY_REQUEST_FAIL = "ADD_CATEGORY_REQUEST_FAIL";

export const GET_ALL_CATEGORY_REQUEST_SEND = "GET_ALL_CATEGORY_REQUEST_SEND";
export const GET_ALL_CATEGORY_REQUEST_SUCCESS = "GET_ALL_CATEGORY_REQUEST_SUCCESS";
export const GET_ALL_CATEGORY_REQUEST_FAIL = "GET_ALL_CATEGORY_REQUEST_FAIL";

export const EDIT_CATEGORY_REQUEST_SEND = "EDIT_CATEGORY_REQUEST_SEND";
export const EDIT_CATEGORY_REQUEST_SUCCESS = "EDIT_CATEGORY_REQUEST_SUCCESS";
export const EDIT_CATEGORY_REQUEST_FAIL = "EDIT_CATEGORY_REQUEST_FAIL";

// SUB CATEGORY 

export const ADD_SUB_CATEGORY_REQUEST_SEND = "ADD_SUB_CATEGORY_REQUEST_SEND";
export const ADD_SUB_CATEGORY_REQUEST_SUCCESS = "ADD_SUB_CATEGORY_REQUEST_SUCCESS";
export const ADD_SUB_CATEGORY_REQUEST_FAIL = "ADD_SUB_CATEGORY_REQUEST_FAIL";

export const GET_ALL_SUB_CATEGORY_REQUEST_SEND = "GET_ALL_SUB_CATEGORY_REQUEST_SEND";
export const GET_ALL_SUB_CATEGORY_REQUEST_SUCCESS = "GET_ALL_SUB_CATEGORY_REQUEST_SUCCESS";
export const GET_ALL_SUB_CATEGORY_REQUEST_FAIL = "GET_ALL_SUB_CATEGORY_REQUEST_FAIL";

export const EDIT_SUB_CATEGORY_REQUEST_SEND = "EDIT_SUB_CATEGORY_REQUEST_SEND";
export const EDIT_SUB_CATEGORY_REQUEST_SUCCESS = "EDIT_SUB_CATEGORY_REQUEST_SUCCESS";
export const EDIT_SUB_CATEGORY_REQUEST_FAIL = "EDIT_SUB_CATEGORY_REQUEST_FAIL";

export const DELETE_SUB_CATEGORY_REQUEST_SEND = "DELETE_SUB_CATEGORY_REQUEST_SEND";
export const DELETE_SUB_CATEGORY_REQUEST_SUCCESS = "DELETE_SUB_CATEGORY_REQUEST_SUCCESS";
export const DELETE_SUB_CATEGORY_REQUEST_FAIL = "DELETE_SUB_CATEGORY_REQUEST_FAIL";


// SELLER 

export const ADD_SELLER_REQUEST_SEND = "ADD_SELLER_REQUEST_SEND";
export const ADD_SELLER_REQUEST_SUCCESS = "ADD_SELLER_REQUEST_SUCCESS";
export const ADD_SELLER_REQUEST_FAIL = "ADD_SELLER_REQUEST_FAIL";

export const EDIT_SELLER_REQUEST_SEND = "EDIT_SELLER_REQUEST_SEND";
export const EDIT_SELLER_REQUEST_SUCCESS = "EDIT_SELLER_REQUEST_SUCCESS";
export const EDIT_SELLER_REQUEST_FAIL = "EDIT_SELLER_REQUEST_FAIL";

export const GET_ALL_SELLER_REQUEST_SEND = "GET_ALL_SELLER_REQUEST_SEND";
export const GET_ALL_SELLER_REQUEST_SUCCESS = "GET_ALL_SELLER_REQUEST_SUCCESS";
export const GET_ALL_SELLER_REQUEST_FAIL = "GET_ALL_SELLER_REQUEST_FAIL";

export const DELETE_SELLER_REQUEST_SEND = "DELETE_SELLER_REQUEST_SEND";
export const DELETE_SELLER_REQUEST_SUCCESS = "DELETE_SELLER_REQUEST_SUCCESS";
export const DELETE_SELLER_REQUEST_FAIL = "DELETE_SELLER_REQUEST_FAIL";

// SHOP 

export const ADD_SHOP_REQUEST_SEND = "ADD_SHOP_REQUEST_SEND";
export const ADD_SHOP_REQUEST_SUCCESS = "ADD_SHOP_REQUEST_SUCCESS";
export const ADD_SHOP_REQUEST_FAIL = "ADD_SHOP_REQUEST_FAIL";

export const GET_ALL_SHOP_REQUEST_SEND = "GET_ALL_SHOP_REQUEST_SEND";
export const GET_ALL_SHOP_REQUEST_SUCCESS = "GET_ALL_SHOP_REQUEST_SUCCESS";
export const GET_ALL_SHOP_REQUEST_FAIL = "GET_ALL_SHOP_REQUEST_FAIL";

export const EDIT_SHOP_REQUEST_SEND = "EDIT_SHOP_REQUEST_SEND";
export const EDIT_SHOP_REQUEST_SUCCESS = "EDIT_SHOP_REQUEST_SUCCESS";
export const EDIT_SHOP_REQUEST_FAIL = "EDIT_SHOP_REQUEST_FAIL";

export const DELETE_SHOP_REQUEST_SEND = "DELETE_SHOP_REQUEST_SEND";
export const DELETE_SHOP_REQUEST_SUCCESS = "DELETE_SHOP_REQUEST_SUCCESS";
export const DELETE_SHOP_REQUEST_FAIL = "DELETE_SHOP_REQUEST_FAIL";

export const SHOP_LIVE_STATUS_REQUEST_SEND = "SHOP_LIVE_STATUS_REQUEST_SEND";
export const SHOP_LIVE_STATUS_REQUEST_SUCCESS = "SHOP_LIVE_STATUS_REQUEST_SUCCESS";
export const SHOP_LIVE_STATUS_REQUEST_FAIL = "SHOP_LIVE_STATUS_REQUEST_FAIL";

export const ADD_CUISINE_REQUEST_SEND = "ADD_CUISINE_REQUEST_SEND";
export const ADD_CUISINE_REQUEST_SUCCESS = "ADD_CUISINE_REQUEST_SUCCESS";
export const ADD_CUISINE_REQUEST_FAIL = "ADD_CUISINE_REQUEST_FAIL"

export const ALL_CUISINES_REQUEST_SEND = "ALL_CUISINES_REQUEST_SEND";
export const ALL_CUISINES_REQUEST_SUCCESS = "ALL_CUISINES_REQUEST_SUCCESS";
export const ALL_CUISINES_REQUEST_FAIL = "ALL_CUISINES_REQUEST_FAIL"

export const EDIT_CUISINE_REQUEST_SEND = "EDIT_CUISINE_REQUEST_SEND";
export const EDIT_CUISINE_REQUEST_SUCCESS = "EDIT_CUISINE_REQUEST_SUCCESS";
export const EDIT_CUISINE_REQUEST_FAIL = "EDIT_CUISINE_REQUEST_FAIL"

// PRODUCT 

export const ADD_PRODUCT_REQUEST_SEND = "ADD_PRODUCT_REQUEST_SEND";
export const ADD_PRODUCT_REQUEST_SUCCESS = "ADD_PRODUCT_REQUEST_SUCCESS";
export const ADD_PRODUCT_REQUEST_FAIL = "ADD_PRODUCT_REQUEST_FAIL";

export const GET_ALL_PRODUCT_REQUEST_SEND = "GET_ALL_PRODUCT_REQUEST_SEND";
export const GET_ALL_PRODUCT_REQUEST_SUCCESS = "GET_ALL_PRODUCT_REQUEST_SUCCESS";
export const GET_ALL_PRODUCT_REQUEST_FAIL = "GET_ALL_PRODUCT_REQUEST_FAIL";

export const EDIT_PRODUCT_REQUEST_SEND = "EDIT_PRODUCT_REQUEST_SEND";
export const EDIT_PRODUCT_REQUEST_SUCCESS = "EDIT_PRODUCT_REQUEST_SUCCESS";
export const EDIT_PRODUCT_REQUEST_FAIL = "EDIT_PRODUCT_REQUEST_FAIL";


export const DELETE_PRODUCT_REQUEST_SEND = "DELETE_PRODUCT_REQUEST_SEND";
export const DELETE_PRODUCT_REQUEST_SUCCESS = "DELETE_PRODUCT_REQUEST_SUCCESS";
export const DELETE_PRODUCT_REQUEST_FAIL = "DELETE_PRODUCT_REQUEST_FAIL";

// DELIVERY MAN 

export const ADD_DELIVERY_MAN_REQUEST_SEND = "ADD_DELIVERY_MAN_REQUEST_SEND";
export const ADD_DELIVERY_MAN_REQUEST_SUCCESS = "ADD_DELIVERY_MAN_REQUEST_SUCCESS";
export const ADD_DELIVERY_MAN_REQUEST_FAIL = "ADD_DELIVERY_MAN_REQUEST_FAIL"

export const ALL_DELIVERY_MAN_REQUEST_SEND = "ALL_DELIVERY_MAN_REQUEST_SEND";
export const ALL_DELIVERY_MAN_REQUEST_SUCCESS = "ALL_DELIVERY_MAN_REQUEST_SUCCESS";
export const ALL_DELIVERY_MAN_REQUEST_FAIL = "ALL_DELIVERY_MAN_REQUEST_FAIL"

export const EDIT_DELIVERY_MAN_REQUEST_SEND = "EDIT_DELIVERY_MAN_REQUEST_SEND";
export const EDIT_DELIVERY_MAN_REQUEST_SUCCESS = "EDIT_DELIVERY_MAN_REQUEST_SUCCESS";
export const EDIT_DELIVERY_MAN_REQUEST_FAIL = "EDIT_DELIVERY_MAN_REQUEST_FAIL"


// ADMIN SETTINGS 

export const UPDATE_GOOGLE_KEY = "UPDATE_GOOGLE_KEY"
export const ALL_ADMIN_SETTINGS_REQUEST_SEND = "ALL_ADMIN_SETTINGS_REQUEST_SEND";
export const ALL_ADMIN_SETTINGS_REQUEST_SUCCESS = "ALL_ADMIN_SETTINGS_REQUEST_SUCCESS";
export const ALL_ADMIN_SETTINGS_REQUEST_FAIL = "ALL_ADMIN_SETTINGS_REQUEST_FAIL"

export const UPDATE_ADMIN_SETTINGS_REQUEST_SEND = "UPDATE_ADMIN_SETTINGS_REQUEST_SEND";
export const UPDATE_ADMIN_SETTINGS_REQUEST_SUCCESS = "UPDATE_ADMIN_SETTINGS_REQUEST_SUCCESS";
export const UPDATE_ADMIN_SETTINGS_REQUEST_FAIL = "UPDATE_ADMIN_SETTINGS_REQUEST_FAIL"

// IMAGE UPLOAD 

export const IMAGE_UPLOAD_REQUEST_SEND = "IMAGE_UPLOAD_REQUEST_SEND";
export const IMAGE_UPLOAD_REQUEST_SUCCESS = "IMAGE_UPLOAD_REQUEST_SUCCESS";
export const IMAGE_UPLOAD_REQUEST_FAIL = "IMAGE_UPLOAD_REQUEST_FAIL";

// FILTER KEY

export const UPDATE_SEARCH_KEY = "UPDATE_SEARCH_KEY";
export const UPDATE_STATUS_KEY = "UPDATE_STATUS_KEY";
export const UPDATE_SORT_BY_KEY = "UPDATE_SORT_BY_KEY";
export const UPDATE_TYPE_KEY = "UPDATE_TYPE_KEY";
export const UPDATE_CREATED_BY_KEY = "UPDATE_CREATED_BY_KEY";
export const UPDATE_CURRENT_STATUS_KEY = "UPDATE_CURRENT_STATUS_KEY";
export const SET_STATUS_FALSE = "SET_STATUS_FALSE";
export const UPDATE_PRODUCT_VISIBILITY_KEY = "UPDATE_PRODUCT_VISIBILITY_KEY";
export const UPDATE_SELLER_SUB_TYPE = "UPDATE_SELLER_SUB_TYPE";
export const UPDATE_SHOP_LIVE_STATUS = "UPDATE_SHOP_LIVE_STATUS";








