export const UPLOAD_IMAGE_REQUEST_SEND = "UPLOAD_IMAGE_REQUEST_SEND";
export const UPLOAD_IMAGE_REQUEST_SUCCESS = "UPLOAD_IMAGE_REQUEST_SUCCESS";
export const UPLOAD_IMAGE_REQUEST_FAIL = "UPLOAD_IMAGE_REQUEST_FAIL";
export const SELECT_IMAGE = "SELECT_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const SELECT_FOLDER = "SELECT_FOLDER";
export const ADD_LIST_FOLDER = "ADD_LIST_FOLDER";
export const IMAGE_SELECTION_ERROR = "IMAGE_SELECTION_ERROR";
export const UPLOAD_IMAGE_DONE = "UPLOAD_IMAGE_DONE";

export const IMAGE_GALLEY_MARK_SELECT = "IMAGE_GALLEY_MARK_SELECT";
export const IMAGE_GALLEY_MARK_REMOVE = "IMAGE_GALLEY_MARK_REMOVE";
export const IMAGE_GALLEY_MARK_REMOVE_ALL = "IMAGE_GALLEY_MARK_REMOVE_ALL";

export const IMAGE_GALLEY_LIST_REQUEST_SEND = "IMAGE_GALLEY_LIST_REQUEST_SEND";
export const IMAGE_GALLEY_LIST_REQUEST_SUCCESS =
  "IMAGE_GALLEY_LIST_REQUEST_SUCCESS";
export const IMAGE_GALLEY_LIST_REQUEST_FAIL = "IMAGE_GALLEY_LIST_REQUEST_FAIL";

export const IMAGE_FOLDER_LIST_REQUEST_SEND = "IMAGE_FOLDER_REQUEST_SEND";
export const IMAGE_FOLDER_LIST_REQUEST_SUCCESS = "IMAGE_FOLDER_REQUEST_SUCCESS";
export const IMAGE_FOLDER_LIST_REQUEST_FAIL = "IMAGE_FOLDER_REQUEST_FAIL";
export const IMAGE_FOLDER_LIST_ADD = "IMAGE_FOLDER_LIST_ADD";

export const IMAGE_FOLDER_ADD_REQUEST_SEND = "IMAGE_FOLDER_ADD_REQUEST_SEND";
export const IMAGE_FOLDER_ADD_REQUEST_SUCCESS =
  "IMAGE_FOLDER_ADD_REQUEST_SUCCESS";
export const IMAGE_FOLDER_ADD_REQUEST_FAIL = "IMAGE_FOLDER_ADD_REQUEST_FAIL";

// dashboard
export const GET_DASHBOARD_SUMMARY_REQUEST_SEND =
  "GET_DASHBOARD_SUMMARY_REQUEST_SEND";
export const GET_DASHBOARD_SUMMARY_REQUEST_SUCCESS =
  "GET_DASHBOARD_SUMMARY_REQUEST_SUCCESS";
export const GET_DASHBOARD_SUMMARY_REQUEST_FAIL =
  "GET_DASHBOARD_SUMMARY_REQUEST_FAIL";

//banner
export const BANNER_REQUEST_SEND = "BANNER_REQUEST_SEND";
export const BANNER_REQUEST_SUCCESS = "BANNER_REQUEST_SUCCESS";
export const BANNER_REQUEST_FAIL = "BANNER_REQUEST_FAIL";
export const BANNER_REQUEST_ADD = "BANNER_REQUEST_ADD";
export const OPEN_EDIT_PAGE = "OPEN_EDIT_PAGE";

export const BANNER_ADD_REQUEST_SENT = "BANNER_ADD_REQUEST_SENT";
export const BANNER_ADD_REQUEST_FAIL = "BANNER_ADD_REQUEST_FAIL";
export const BANNER_ADD_REQUEST_SUCCESS = "BANNER_ADD_REQUEST_SUCCESS";
export const BANNER_MESSAGE_CLEAR = "BANNER_MESSAGE_CLEAR";
export const BANNER_FILTER_SELECT = "BANNER_FILTER_SELECT";

export const EDIT_BANNER_REQUEST_SEND = "EDIT_BANNER_REQUEST_SEND";
export const EDIT_BANNER_REQUEST_SUCCESS = "EDIT_BANNER_REQUEST_SUCCESS";
export const GET_EDITED_BANNER = "GET_EDITED_BANNER";
export const EDIT_BANNER_REQUEST_FAIL = "EDIT_BANNER_REQUEST_FAIL";

export const DELETE_BANNER_REQUEST_SEND = "DELETE_BANNER_REQUEST_SEND";
export const DELETE_BANNER_REQUEST_SUCCESS = "DELETE_BANNER_REQUEST_SUCCESS";
export const DELETE_BANNER_REQUEST_FAIL = "DELETE_BANNER_REQUEST_FAIL";

// ADMIN

export const ADD_ADMIN_REQUEST_SEND = "ADD_ADMIN_REQUEST_SEND";
export const ADD_ADMIN_REQUEST_SUCCESS = "ADD_ADMIN_REQUEST_SUCCESS";
export const ADD_ADMIN_REQUEST_FAIL = "ADD_ADMIN_REQUEST_FAIL";

export const GET_ALL_ADMIN_REQUEST_SEND = "GET_ALL_ADMIN_REQUEST_SEND";
export const GET_ALL_ADMIN_REQUEST_SUCCESS = "GET_ALL_ADMIN_REQUEST_SUCCESS";
export const GET_ALL_ADMIN_REQUEST_FAIL = "GET_ALL_ADMIN_REQUEST_FAIL";

export const DELETE_ADMIN_REQUEST_SEND = "DELETE_ADMIN_REQUEST_SEND";
export const DELETE_ADMIN_REQUEST_SUCCESS = "DELETE_ADMIN_REQUEST_SUCCESS";
export const DELETE_ADMIN_REQUEST_FAIL = "DELETE_ADMIN_REQUEST_FAIL";

export const EDIT_ADMIN_REQUEST_SEND = "EDIT_ADMIN_REQUEST_SEND";
export const EDIT_ADMIN_REQUEST_SUCCESS = "EDIT_ADMIN_REQUEST_SUCCESS";
export const EDIT_ADMIN_REQUEST_FAIL = "EDIT_ADMIN_REQUEST_FAIL";

// ROLE

export const CREATE_ADMIN_ROLE_REQUEST_SEND = "CREATE_ADMIN_ROLE_REQUEST_SEND";
export const CREATE_ADMIN_ROLE_REQUEST_SUCCESS =
  "CREATE_ADMIN_ROLE_REQUEST_SUCCESS";
export const CREATE_ADMIN_ROLE_REQUEST_FAIL = "CREATE_ADMIN_ROLE_REQUEST_FAIL";
export const GET_CREATED_ADMIN_ROLE = "GET_CREATED_ADMIN_ROLE";

export const GET_ALL_ROLE_REQUEST_SEND = "GET_ALL_ROLE_REQUEST_SEND";
export const GET_ALL_ROLE_REQUEST_SUCCESS = "GET_ALL_ROLE_REQUEST_SUCCESS";
export const GET_ALL_ROLE_REQUEST_FAIL = "GET_ALL_ROLE_REQUEST_FAIL";

export const EDIT_ADMIN_ROLE_REQUEST_SEND = "EDIT_ADMIN_ROLE_REQUEST_SEND";
export const EDIT_ADMIN_ROLE_REQUEST_SUCCESS =
  "EDIT_ADMIN_ROLE_REQUEST_SUCCESS";
export const EDIT_ADMIN_ROLE_REQUEST_FAIL = "EDIT_ADMIN_ROLE_REQUEST_FAIL";
export const GET_UPDATE_ADMIN_ROLE = "GET_UPDATE_ADMIN_ROLE";

export const DELETE_ROLE_REQUEST_SEND = "DELETE_ROLE_REQUEST_SEND";
export const DELETE_ROLE_REQUEST_SUCCESS = "DELETE_ROLE_REQUEST_SUCCESS";
export const DELETE_ROLE_REQUEST_FAIL = "DELETE_ROLE_REQUEST_FAIL";

export const RESTORE_ROLE_REQUEST_SEND = "RESTORE_ROLE_REQUEST_SEND";
export const RESTORE_ROLE_REQUEST_SUCCESS = "RESTORE_ROLE_REQUEST_SUCCESS";
export const RESTORE_ROLE_REQUEST_FAIL = "RESTORE_ROLE_REQUEST_FAIL";

export const ADD_SELLER_CREDENTIAL_REQUEST_SEND =
  "ADD_SELLER_CREDENTIAL_REQUEST_SEND";
export const ADD_SELLER_CREDENTIAL_REQUEST_SUCCESS =
  "ADD_SELLER_CREDENTIAL_REQUEST_SUCCESS";
export const ADD_SELLER_CREDENTIAL_REQUEST_FAIL =
  "ADD_SELLER_CREDENTIAL_REQUEST_FAIL";

export const GET_SELLER_CREDENTIALS_REQUEST_SEND =
  "GET_SELLER_CREDENTIALS_REQUEST_SEND";
export const GET_SELLER_CREDENTIALS_REQUEST_SUCCESS =
  "GET_SELLER_CREDENTIALS_REQUEST_SUCCESS";
export const GET_SELLER_CREDENTIALS_REQUEST_FAIL =
  "GET_SELLER_CREDENTIALS_REQUEST_FAIL";

export const REMOVE_SELLER_CREDENTIAL_REQUEST_SEND =
  "REMOVE_SELLER_CREDENTIAL_REQUEST_SEND";
export const REMOVE_SELLER_CREDENTIAL_REQUEST_SUCCESS =
  "REMOVE_SELLER_CREDENTIAL_REQUEST_SUCCESS";
export const REMOVE_SELLER_CREDENTIAL_REQUEST_FAIL =
  "REMOVE_SELLER_CREDENTIAL_REQUEST_FAIL";

export const ADD_SHOP_CREDENTIAL_REQUEST_SEND =
  "ADD_SHOP_CREDENTIAL_REQUEST_SEND";
export const ADD_SHOP_CREDENTIAL_REQUEST_SUCCESS =
  "ADD_SHOP_CREDENTIAL_REQUEST_SUCCESS";
export const ADD_SHOP_CREDENTIAL_REQUEST_FAIL = "ADD_S_CREDENTIAL_REQUEST_FAIL";

export const GET_SHOP_CREDENTIALS_REQUEST_SEND =
  "GET_SHOP_CREDENTIALS_REQUEST_SEND";
export const GET_SHOP_CREDENTIALS_REQUEST_SUCCESS =
  "GET_SHOP_CREDENTIALS_REQUEST_SUCCESS";
export const GET_SHOP_CREDENTIALS_REQUEST_FAIL =
  "GET_SHOP_CREDENTIALS_REQUEST_FAIL";

export const REMOVE_SHOP_CREDENTIAL_REQUEST_SEND =
  "REMOVE_SHOP_CREDENTIAL_REQUEST_SEND";
export const REMOVE_SHOP_CREDENTIAL_REQUEST_SUCCESS =
  "REMOVE_SHOP_CREDENTIAL_REQUEST_SUCCESS";
export const REMOVE_SHOP_CREDENTIAL_REQUEST_FAIL =
  "REMOVE_SHOP_CREDENTIAL_REQUEST_FAIL";

// USERS

export const GET_ALL_USERS_REQUEST_SEND = "GET_ALL_USERS_REQUEST_SEND";
export const GET_ALL_USERS_REQUEST_SUCCESS = "GET_ALL_USERS_REQUEST_SUCCESS";
export const GET_ALL_USERS_REQUEST_FAIL = "GET_ALL_USERS_REQUEST_FAIL";

export const ADD_USER_REQUEST_SEND = "ADD_USER_REQUEST_SEND";
export const ADD_USER_REQUEST_SUCCESS = "ADD_USER_REQUEST_SUCCESS";
export const ADD_USER_REQUEST_FAIL = "ADD_USER_REQUEST_FAIL";

export const EDIT_USER_REQUEST_SEND = "EDIT_USER_REQUEST_SEND";
export const EDIT_USER_REQUEST_SUCCESS = "EDIT_USER_REQUEST_SUCCESS";
export const EDIT_USER_REQUEST_FAIL = "EDIT_USER_REQUEST_FAIL";

export const USER_TRANSACTIONS_REQUEST_SEND = "USER_TRANSACTION_REQUEST_SEND";
export const USER_TRANSACTIONS_REQUEST_SUCCESS =
  "USER_TRANSACTION_REQUEST_SUCCESS";
export const USER_TRANSACTIONS_REQUEST_FAIL = "USER_TRANSACTION_REQUEST_FAIL";

export const UPDATE_USERS_SORT_KEY = "UPDATE_USERS_SORT_KEY";
export const UPDATE_USERS_SEARCH_KEY = "UPDATE_USERS_SEARCH_KEY";

export const USER_ORDERS_REQUEST_SEND = "USER_ORDERS_REQUEST_SEND";
export const USER_ORDERS_REQUEST_SUCCESS = "USER_ORDERS_REQUEST_SUCCESS";
export const USER_ORDERS_REQUEST_FAIL = "USER_ORDERS_RORDERS_REQUEST_FAI";

export const UPDATE_USER_STATUS_REQUEST_SEND = "USER_STATUS_REQUEST_SEND";
export const UPDATE_USER_STATUS_REQUEST_SUCCESS = "USER_STATUS_REQUEST_SUCCESS";
export const UPDATE_USER_STATUS_REQUEST_FAIL =
  "USER_STATUS_RORDERS_REQUEST_FAI";

// CATEGORY

export const ADD_CATEGORY_REQUEST_SEND = "ADD_CATEGORY_REQUEST_SEND";
export const ADD_CATEGORY_REQUEST_SUCCESS = "ADD_CATEGORY_REQUEST_SUCCESS";
export const ADD_CATEGORY_REQUEST_FAIL = "ADD_CATEGORY_REQUEST_FAIL";

export const GET_ALL_CATEGORY_REQUEST_SEND = "GET_ALL_CATEGORY_REQUEST_SEND";
export const GET_ALL_CATEGORY_REQUEST_SUCCESS =
  "GET_ALL_CATEGORY_REQUEST_SUCCESS";
export const GET_ALL_CATEGORY_REQUEST_FAIL = "GET_ALL_CATEGORY_REQUEST_FAIL";

export const EDIT_CATEGORY_REQUEST_SEND = "EDIT_CATEGORY_REQUEST_SEND";
export const EDIT_CATEGORY_REQUEST_SUCCESS = "EDIT_CATEGORY_REQUEST_SUCCESS";
export const EDIT_CATEGORY_REQUEST_FAIL = "EDIT_CATEGORY_REQUEST_FAIL";

export const UPTATE_CATEGORY_SHOP_TYEP_KEY = "UPTATE_CATEGORY_SHOP_TYEP_KEY";

// SUB CATEGORY

export const ADD_SUB_CATEGORY_REQUEST_SEND = "ADD_SUB_CATEGORY_REQUEST_SEND";
export const ADD_SUB_CATEGORY_REQUEST_SUCCESS =
  "ADD_SUB_CATEGORY_REQUEST_SUCCESS";
export const ADD_SUB_CATEGORY_REQUEST_FAIL = "ADD_SUB_CATEGORY_REQUEST_FAIL";

export const GET_ALL_SUB_CATEGORY_REQUEST_SEND =
  "GET_ALL_SUB_CATEGORY_REQUEST_SEND";
export const GET_ALL_SUB_CATEGORY_REQUEST_SUCCESS =
  "GET_ALL_SUB_CATEGORY_REQUEST_SUCCESS";
export const GET_ALL_SUB_CATEGORY_REQUEST_FAIL =
  "GET_ALL_SUB_CATEGORY_REQUEST_FAIL";

export const EDIT_SUB_CATEGORY_REQUEST_SEND = "EDIT_SUB_CATEGORY_REQUEST_SEND";
export const EDIT_SUB_CATEGORY_REQUEST_SUCCESS =
  "EDIT_SUB_CATEGORY_REQUEST_SUCCESS";
export const EDIT_SUB_CATEGORY_REQUEST_FAIL = "EDIT_SUB_CATEGORY_REQUEST_FAIL";

export const DELETE_SUB_CATEGORY_REQUEST_SEND =
  "DELETE_SUB_CATEGORY_REQUEST_SEND";
export const DELETE_SUB_CATEGORY_REQUEST_SUCCESS =
  "DELETE_SUB_CATEGORY_REQUEST_SUCCESS";
export const DELETE_SUB_CATEGORY_REQUEST_FAIL =
  "DELETE_SUB_CATEGORY_REQUEST_FAIL";

// SELLER

export const ADD_SELLER_REQUEST_SEND = "ADD_SELLER_REQUEST_SEND";
export const ADD_SELLER_REQUEST_SUCCESS = "ADD_SELLER_REQUEST_SUCCESS";
export const ADD_SELLER_REQUEST_FAIL = "ADD_SELLER_REQUEST_FAIL";

export const EDIT_SELLER_REQUEST_SEND = "EDIT_SELLER_REQUEST_SEND";
export const EDIT_SELLER_REQUEST_SUCCESS = "EDIT_SELLER_REQUEST_SUCCESS";
export const EDIT_SELLER_REQUEST_FAIL = "EDIT_SELLER_REQUEST_FAIL";

export const GET_ALL_SELLER_REQUEST_SEND = "GET_ALL_SELLER_REQUEST_SEND";
export const GET_ALL_SELLER_REQUEST_SUCCESS = "GET_ALL_SELLER_REQUEST_SUCCESS";
export const GET_ALL_SELLER_REQUEST_FAIL = "GET_ALL_SELLER_REQUEST_FAIL";

export const DELETE_SELLER_REQUEST_SEND = "DELETE_SELLER_REQUEST_SEND";
export const DELETE_SELLER_REQUEST_SUCCESS = "DELETE_SELLER_REQUEST_SUCCESS";
export const DELETE_SELLER_REQUEST_FAIL = "DELETE_SELLER_REQUEST_FAIL";

export const ADD_SELLER_DROP_CHARGE_REQUEST_SEND =
  "ADD_SELLER_DROP_CHARGE_REQUEST_SEND";
export const ADD_SELLER_DROP_CHARGE_REQUEST_SUCCESS =
  "ADD_SELLER_DROP_CHARGE_REQUEST_SUCCESS";
export const ADD_SELLER_DROP_CHARGE_REQUEST_FAIL =
  "ADD_SELLER_DROP_CHARGE_REQUEST_FAIL";

// SHOP

export const ADD_SHOP_REQUEST_SEND = "ADD_SHOP_REQUEST_SEND";
export const ADD_SHOP_REQUEST_SUCCESS = "ADD_SHOP_REQUEST_SUCCESS";
export const ADD_SHOP_REQUEST_FAIL = "ADD_SHOP_REQUEST_FAIL";

export const GET_ALL_SHOP_REQUEST_SEND = "GET_ALL_SHOP_REQUEST_SEND";
export const GET_ALL_SHOP_REQUEST_SUCCESS = "GET_ALL_SHOP_REQUEST_SUCCESS";
export const GET_ALL_SHOP_REQUEST_FAIL = "GET_ALL_SHOP_REQUEST_FAIL";

export const EDIT_SHOP_REQUEST_SEND = "EDIT_SHOP_REQUEST_SEND";
export const EDIT_SHOP_REQUEST_SUCCESS = "EDIT_SHOP_REQUEST_SUCCESS";
export const EDIT_SHOP_REQUEST_FAIL = "EDIT_SHOP_REQUEST_FAIL";

export const DELETE_SHOP_REQUEST_SEND = "DELETE_SHOP_REQUEST_SEND";
export const DELETE_SHOP_REQUEST_SUCCESS = "DELETE_SHOP_REQUEST_SUCCESS";
export const DELETE_SHOP_REQUEST_FAIL = "DELETE_SHOP_REQUEST_FAIL";

export const SHOP_LIVE_STATUS_REQUEST_SEND = "SHOP_LIVE_STATUS_REQUEST_SEND";
export const SHOP_LIVE_STATUS_REQUEST_SUCCESS =
  "SHOP_LIVE_STATUS_REQUEST_SUCCESS";
export const SHOP_LIVE_STATUS_REQUEST_FAIL = "SHOP_LIVE_STATUS_REQUEST_FAIL";

export const ADD_CUISINE_REQUEST_SEND = "ADD_CUISINE_REQUEST_SEND";
export const ADD_CUISINE_REQUEST_SUCCESS = "ADD_CUISINE_REQUEST_SUCCESS";
export const ADD_CUISINE_REQUEST_FAIL = "ADD_CUISINE_REQUEST_FAIL";

export const ALL_CUISINES_REQUEST_SEND = "ALL_CUISINES_REQUEST_SEND";
export const ALL_CUISINES_REQUEST_SUCCESS = "ALL_CUISINES_REQUEST_SUCCESS";
export const ALL_CUISINES_REQUEST_FAIL = "ALL_CUISINES_REQUEST_FAIL";

export const EDIT_CUISINE_REQUEST_SEND = "EDIT_CUISINE_REQUEST_SEND";
export const EDIT_CUISINE_REQUEST_SUCCESS = "EDIT_CUISINE_REQUEST_SUCCESS";
export const EDIT_CUISINE_REQUEST_FAIL = "EDIT_CUISINE_REQUEST_FAIL";

export const ADD_SHOP_DEAL_REQUEST_SEND = "ADD_SHOP_DEAL_REQUEST_SEND";
export const ADD_SHOP_DEAL_REQUEST_SUCCESS = "ADD_SHOP_DEAL_REQUEST_SUCCESS";
export const ADD_SHOP_DEAL_REQUEST_FAIL = "ADD_SHOP_DEAL_REQUEST_FAIL";

export const SET_FEATURED_SHOP_REQUEST_SEND = "SET_FEATURED_SHOP_REQUEST_SEND";
export const SET_FEATURED_SHOP_REQUEST_SUCCESS =
  "SET_FEATURED_SHOP_REQUEST_SUCCESS";
export const SET_FEATURED_SHOP_REQUEST_FAIL = "SET_FEATURED_SHOP_REQUEST_FAIL";

export const UPDATE_SHOP_STATUS_KEY = "UPDATE_SHOP_STATUS_KEY";
export const UPDATE_SHOP_SORT_BY_KEY = "UPDATE_SHOP_SORT_BY_KEY";
export const UPDATE_SHOP_TYPE_KEY = "UPDATE_SHOP_TYPE_KEY";

export const DELETE_SHOP_DEAL_REQUEST_SEND = "DELETE_SHOP_DEAL_REQUEST_SEND";
export const DELETE_SHOP_DEAL_REQUEST_SUCCESS =
  "DELETE_SHOP_DEAL_REQUEST_SUCCESS";
export const DELETE_SHOP_DEAL_REQUEST_FAIL = "DELETE_SHOP_DEAL_REQUEST_FAIL";

export const UPDATE_SHOP_STATUS_REQUEST_SEND =
  "UPDATE_SHOP_STATUS_REQUEST_SEND";
export const UPDATE_SHOP_STATUS_REQUEST_SUCCESS =
  "UPDATE_SHOP_STATUS_REQUEST_SUCCESS";
export const UPDATE_SHOP_STATUS_REQUEST_FAIL =
  "UPDATE_SHOP_STATUS_REQUEST_FAIL";

// PRODUCT

export const ADD_PRODUCT_REQUEST_SEND = "ADD_PRODUCT_REQUEST_SEND";
export const ADD_PRODUCT_REQUEST_SUCCESS = "ADD_PRODUCT_REQUEST_SUCCESS";
export const ADD_PRODUCT_REQUEST_FAIL = "ADD_PRODUCT_REQUEST_FAIL";

export const GET_ALL_PRODUCT_REQUEST_SEND = "GET_ALL_PRODUCT_REQUEST_SEND";
export const GET_ALL_PRODUCT_REQUEST_SUCCESS =
  "GET_ALL_PRODUCT_REQUEST_SUCCESS";
export const GET_ALL_PRODUCT_REQUEST_FAIL = "GET_ALL_PRODUCT_REQUEST_FAIL";

export const EDIT_PRODUCT_REQUEST_SEND = "EDIT_PRODUCT_REQUEST_SEND";
export const EDIT_PRODUCT_REQUEST_SUCCESS = "EDIT_PRODUCT_REQUEST_SUCCESS";
export const EDIT_PRODUCT_REQUEST_FAIL = "EDIT_PRODUCT_REQUEST_FAIL";

export const UPDATE_PRODUCT_STATUS_REQUEST_SEND =
  "UPDATE_PRODUCT_STATUS_REQUEST_SEND";
export const UPDATE_PRODUCT_STATUS_REQUEST_SUCCESS =
  "UPDATE_PRODUCT_STATUS_REQUEST_SUCCESS";
export const UPDATE_PRODUCT_STATUS_REQUEST_FAIL =
  "UPDATE_PRODUCT_STATUS_REQUEST_FAIL";

export const ADD_PRODUCT_DEAL_REQUEST_SEND = "ADD_PRODUCT_DEAL_REQUEST_SEND";
export const ADD_PRODUCT_DEAL_REQUEST_SUCCESS =
  "ADD_PRODUCT_DEAL_REQUEST_SUCCESS";
export const ADD_PRODUCT_DEAL_REQUEST_FAIL = "ADD_PRODUCT_DEAL_REQUEST_FAIL";

export const DELETE_PRODUCT_DEAL_REQUEST_SEND =
  "DELETE_PRODUCT_DEAL_REQUEST_SEND";
export const DELETE_PRODUCT_DEAL_REQUEST_SUCCESS =
  "DELETE_PRODUCT_DEAL_REQUEST_SUCCESS";
export const DELETE_PRODUCT_DEAL_REQUEST_FAIL =
  "DELETE_PRODUCT_DEAL_REQUEST_FAIL";

// PRODUCT UNIT TYPE

export const ADD_UNIT_REQUEST_SEND = "ADD_UNIT_REQUEST_SEND";
export const ADD_UNIT_REQUEST_SUCCESS = "ADD_UNIT_REQUEST_SUCCESS";
export const ADD_UNIT_REQUEST_FAIL = "ADD_UNIT_REQUEST_FAIL";

export const GET_ALL_UNIT_REQUEST_SEND = "GET_ALL_UNIT_REQUEST_SEND";
export const GET_ALL_UNIT_REQUEST_SUCCESS = "GET_ALL_UNIT_REQUEST_SUCCESS";
export const GET_ALL_UNIT_REQUEST_FAIL = "GET_ALL_UNIT_REQUEST_FAIL";

export const EDIT_UNIT_REQUEST_SEND = "EDIT_UNIT_REQUEST_SEND";
export const EDIT_UNIT_REQUEST_SUCCESS = "EDIT_UNIT_REQUEST_SUCCESS";
export const EDIT_UNIT_REQUEST_FAIL = "EDIT_UNIT_REQUEST_FAIL";

export const DELETE_UNIT_REQUEST_SEND = "DELETE_UNIT_REQUEST_SEND";
export const DELETE_UNIT_REQUEST_SUCCESS = "DELETE_UNIT_REQUEST_SUCCESS";
export const DELETE_UNIT_REQUEST_FAIL = "DELETE_UNIT_REQUEST_FAIL";

// DELIVERY MAN

export const ADD_DELIVERY_MAN_REQUEST_SEND = "ADD_DELIVERY_MAN_REQUEST_SEND";
export const ADD_DELIVERY_MAN_REQUEST_SUCCESS =
  "ADD_DELIVERY_MAN_REQUEST_SUCCESS";
export const ADD_DELIVERY_MAN_REQUEST_FAIL = "ADD_DELIVERY_MAN_REQUEST_FAIL";

export const ALL_DELIVERY_MAN_REQUEST_SEND = "ALL_DELIVERY_MAN_REQUEST_SEND";
export const ALL_DELIVERY_MAN_REQUEST_SUCCESS =
  "ALL_DELIVERY_MAN_REQUEST_SUCCESS";
export const ALL_DELIVERY_MAN_REQUEST_FAIL = "ALL_DELIVERY_MAN_REQUEST_FAIL";

export const EDIT_DELIVERY_MAN_REQUEST_SEND = "EDIT_DELIVERY_MAN_REQUEST_SEND";
export const EDIT_DELIVERY_MAN_REQUEST_SUCCESS =
  "EDIT_DELIVERY_MAN_REQUEST_SUCCESS";
export const EDIT_DELIVERY_MAN_REQUEST_FAIL = "EDIT_DELIVERY_MAN_REQUEST_FAIL";

export const TRACK_DELIVERY_MAN_REQUEST_SEND =
  "TRACK_DELIVERY_MAN_REQUEST_SEND";
export const TRACK_DELIVERY_MAN_REQUEST_SUCCESS =
  "TRACK_DELIVERY_MAN_REQUEST_SUCCESS";
export const TRACK_DELIVERY_MAN_REQUEST_FAIL =
  "TRACK_DELIVERY_MAN_REQUEST_FAIL";

export const DELIVERYBOY_ORDERS_REQUEST_SEND =
  "DELIVERYBOY_ORDERS_REQUEST_SEND";
export const DELIVERYBOY_ORDERS_REQUEST_SUCCESS =
  "DELIVERYBOY_ORDERS_REQUEST_SUCCESS";
export const DELIVERYBOY_ORDERS_REQUEST_FAIL =
  "DELIVERYBOY_ORDERS_RORDERS_REQUEST_FAI";

export const DELIVERY_MAN_CURRENT_LOCATION_REQUEST_SEND =
  "DELIVERY_MAN_CURRENT_LOCATION_REQUEST_SEND";
export const DELIVERY_MAN_CURRENT_LOCATION_REQUEST_SUCCESS =
  "DELIVERY_MAN_CURRENT_LOCATION_REQUEST_SUCCESS";
export const DELIVERY_MAN_CURRENT_LOCATION_REQUEST_FAIL =
  "DELIVERY_MAN_CURRENT_LOCATION_REQUEST_FAIL";

// SETTINGS

export const UPDATE_GOOGLE_KEY = "UPDATE_GOOGLE_KEY";
export const UPDATE_DELIVERY_FEE = "UPDATE_DELIVERY_FEE";
export const UPDATE_SEARCH_DELIVERY_BOY_KM = "UPDATE_SEARCH_DELIVERY_BOY_KM";
export const REMOVE_SEARCH_DELIVERY_BOY_KM = "REMOVE_SEARCH_DELIVERY_BOY_KM";
export const UPDATE_DROP_CREDIT_LIMIT = "UPDATE_DROP_CREDIT_LIMIT";
export const UPDATE_DROP_CURRENCY = "UPDATE_DROP_CURRENCY";

export const ALL_ADMIN_SETTINGS_REQUEST_SEND =
  "ALL_ADMIN_SETTINGS_REQUEST_SEND";
export const ALL_ADMIN_SETTINGS_REQUEST_SUCCESS =
  "ALL_ADMIN_SETTINGS_REQUEST_SUCCESS";
export const ALL_ADMIN_SETTINGS_REQUEST_FAIL =
  "ALL_ADMIN_SETTINGS_REQUEST_FAIL";

export const UPDATE_ADMIN_SETTINGS_REQUEST_SEND =
  "UPDATE_ADMIN_SETTINGS_REQUEST_SEND";
export const UPDATE_ADMIN_SETTINGS_REQUEST_SUCCESS =
  "UPDATE_ADMIN_SETTINGS_REQUEST_SUCCESS";
export const UPDATE_ADMIN_SETTINGS_REQUEST_FAIL =
  "UPDATE_ADMIN_SETTINGS_REQUEST_FAIL";

export const UPDATE_NEAR_BY_SHOP = "UPDATE_NEAR_BY_SHOP";
export const UPDATE_MAX_DISCOUNT = "UPDATE_MAX_DISCOUNT";

export const UPDATE_APP_SETTINGS_REQUEST_SEND =
  "UPDATE_APP_SETTINGS_REQUEST_SEND";
export const UPDATE_APP_SETTINGS_REQUEST_SUCCESS =
  "UPDATE_APP_SETTINGS_REQUEST_SUCCESS";
export const UPDATE_APP_SETTINGS_REQUEST_FAIL =
  "UPDATE_APP_SETTINGS_REQUEST_FAIL";

export const ALL_APP_SETTINGS_REQUEST_SEND = "ALL_APP_SETTINGS_REQUEST_SEND";
export const ALL_APP_SETTINGS_REQUEST_SUCCESS =
  "ALL_ADPP_SETTINGS_REQUEST_SUCCESS";
export const ALL_APP_SETTINGS_REQUEST_FAIL = "ALL_APP_SETTINGS_REQUEST_FAIL";

export const ADD_REASON_REQUEST_SEND = "ADD_REASON_REQUEST_SEND";
export const ADD_REASON_REQUEST_SUCCESS = "ADD_REASON_REQUEST_SUCCESS";
export const ADD_REASON_REQUEST_FAIL = "ADD_REASON_REQUEST_FAIL";

export const UPDATE_REASON_REQUEST_SEND = "UPDATE_REASON_REQUEST_SEND";
export const UPDATE_REASON_REQUEST_SUCCESS = "UPDATE_REASON_REQUEST_SUCCESS";
export const UPDATE_REASON_REQUEST_FAIL = "UPDATE_REASON_REQUEST_FAIL";

export const DELETE_SELLER_DROP_CHARGE_REQUEST_SEND =
  "DELETE_SELLER_DROP_CHARGE_REQUEST_SEND";
export const DELETE_SELLER_DROP_CHARGE_REQUEST_SUCCESS =
  "DELETE_SELLER_DROP_CHARGE_REQUEST_SUCCESS";
export const DELETE_SELLER_DROP_CHARGE_REQUEST_FAIL =
  "DELETE_SELLER_DROP_CHARGE_REQUEST_FAIL";

export const ALL_REASONS_REQUEST_SEND = "ALL_REASONS_REQUEST_SEND";
export const ALL_REASONS_REQUEST_SUCCESS = "ALL_REASONS_REQUEST_SUCCESS";
export const ALL_REASONS_REQUEST_FAIL = "ALL_REASONS_REQUEST_FAIL";

export const ALL_AMDIN_LOGS_REQUEST_SEND = "ALL_AMDIN_LOG_REQUEST_SEND";
export const ALL_AMDIN_LOGS_REQUEST_SUCCESS = "ALL_AMDIN_LOG_REQUEST_SUCCESS";
export const ALL_AMDIN_LOGS_REQUEST_FAIL = "ALL_AMDIN_LOG_REQUEST_FAIL";

export const UPDATE_ADMIN_LOG_TYPE_KEY = "UPDATE_ADMIN_LOG_TYPE_KEY";
export const UPDATE_ADMIN_SORT_KEY = "UPDATE_ADMIN_SORT_KEY";

export const UPDATE_REASON_STATUS_KEY = "UPDATE_REASON_STATUS_KEY";
export const UPDATE_REASON_TYPE_KEY = "UPDATE_REASON_TYPE_KEY";

export const SELLERS_SPECIAL_DROP_CHARGE_REQUEST_SEND =
  "SELLERS_SPECIAL_DROP_CHARGE_REQUEST_SEND";
export const SELLERS_SPECIAL_DROP_CHARGE_REQUEST_SUCCESS =
  "SELLERS_SPECIAL_DROP_CHARGE_REQUEST_SUCCESS";
export const SELLERS_SPECIAL_DROP_CHARGE_REQUEST_FAIL =
  "SELLERS_SPECIAL_DROP_CHARGE_REQUEST_FAIL";

export const ALL_DEFAULT_CHAT_REQUEST_SEND = "ALL_DEFAULT_CHAT_REQUEST_SEND";
export const ALL_DEFAULT_CHAT_REQUEST_SUCCESS =
  "ALL_DEFAULT_CHAT_REQUEST_SUCCESS";
export const ALL_DEFAULT_CHAT_REQUEST_FAIL = "ALL_DEFAULT_CHAT_REQUEST_FAIL";

export const ADD_DEFAULT_CHAT_REQUEST_SEND = "ADD_DEFAULT_CHAT_REQUEST_SEND";
export const ADD_DEFAULT_CHAT_REQUEST_SUCCESS =
  "ADD_DEFAULT_CHAT_REQUEST_SUCCESS";
export const ADD_DEFAULT_CHAT_REQUEST_FAIL = "ADD_DEFAULT_CHAT_REQUEST_FAIL";

export const EDIT_DEFAULT_CHAT_REQUEST_SEND = "EDIT_DEFAULT_CHAT_REQUEST_SEND";
export const EDIT_DEFAULT_CHAT_REQUEST_SUCCESS =
  "EDIT_DEFAULT_CHAT_REQUEST_SUCCESS";
export const EDIT_DEFAULT_CHAT_REQUEST_FAIL = "EDIT_DEFAULT_CHAT_REQUEST_FAIL";

export const SELECT_DEFAULT_MSG = "SELECT_DEFAULT_MSG";

export const ALL_DATABASE_COLLECTIONS_REQUEST_SEND = 'ALL_DATABASE_COLLECTIONS_REQUEST_SEND';
export const ALL_DATABASE_COLLECTIONS_REQUEST_SUCCESS = 'ALL_DATABASE_COLLECTIONS_REQUEST_SUCCESS';
export const ALL_DATABASE_COLLECTIONS_REQUEST_FAIL = 'ALL_DATABASE_COLLECTIONS_REQUEST_FAIL';

export const DATABASE_COLLECTION_BACKUP_REQUEST_SEND = 'DATABASE_COLLECTION_BACKUP_REQUEST_SEND';
export const DATABASE_COLLECTION_BACKUP_REQUEST_SUCCESS = 'DATABASE_COLLECTION_BACKUP_REQUEST_SUCCESS';
export const DATABASE_COLLECTION_BACKUP_REQUEST_FAIL = 'DATABASE_COLLECTION_BACKUP_REQUEST_FAIL';

export const DATABASE_RESTORE_LAST_COLLECTION_BACKUP_REQUEST_SEND = 'DATABASE_RESTORE_LAST_BACKUP_REQUEST_SEND';
export const DATABASE_RESTORE_LAST_COLLECTION_BACKUP_REQUEST_SUCCESS = 'DATABASE_RESTORE_LAST_BACKUP_REQUEST_SUCCESS';
export const DATABASE_RESTORE_LAST_COLLECTION_BACKUP_REQUEST_FAIL = 'DATABASE_RESTORE_LAST_BACKUP_REQUEST_FAIL';

// DEAL

export const ADD_DEAL_REQUEST_SEND = "ADD_DEAL_REQUEST_SEND";
export const ADD_DEAL_REQUEST_SUCCESS = "ADD_DEAL_REQUEST_SUCCESS";
export const ADD_DEAL_REQUEST_FAIL = "ADD_DEAL_REQUEST_FAIL";

export const ALL_DEAL_REQUEST_SEND = "ALL_DEAL_REQUEST_SEND";
export const ALL_DEAL_REQUEST_SUCCESS = "ALL_DEAL_REQUEST_SUCCESS";
export const ALL_DEAL_REQUEST_FAIL = "ALL_DEAL_REQUEST_FAIL";

export const ALL_DEAL_FOR_ADD_REQUEST_SEND = "ALL_DEAL_FOR_ADD_REQUEST_SEND";
export const ALL_DEAL_FOR_ADD_REQUEST_SUCCESS =
  "ALL_DEAL_FOR_ADD_REQUEST_SUCCESS";
export const ALL_DEAL_FOR_ADD_REQUEST_FAIL = "ALL_DEAL_FOR_ADD_REQUEST_FAIL";

export const EDIT_DEAL_REQUEST_SEND = "EDIT_DEAL_REQUEST_SEND";
export const EDIT_DEAL_REQUEST_SUCCESS = "EDIT_DEAL_REQUEST_SUCCESS";
export const EDIT_DEAL_REQUEST_FAIL = "EDIT_DEAL_REQUEST_FAIL";

export const DELETE_DEAL_REQUEST_SEND = "DELETE_DEAL_REQUEST_SEND";
export const DELETE_DEAL_REQUEST_SUCCESS = "DELETE_DEAL_REQUEST_SUCCESS";
export const DELETE_DEAL_REQUEST_FAIL = "DELETE_DEAL_REQUEST_FAIL";

export const ALL_TAG_REQUEST_SEND = "ALL_TAG_REQUEST_SEND";
export const ALL_TAG_REQUEST_SUCCESS = "ALL_TAG_REQUEST_SUCCESS";
export const ALL_TAG_REQUEST_FAIL = "ALL_TAG_REQUEST_FAIL";

// DROP PAY
export const ALL_DROP_PAY_REQUEST_SEND = "ALL_DROP_PAY_REQUEST_SEND";
export const ALL_DROP_PAY_REQUEST_SUCCESS = "ALL_DROP_PAY_REQUEST_SUCCESS";
export const ALL_DROP_PAY_REQUEST_FAIL = "ALL_DROP_PAY_REQUEST_FAIL";

export const ADD_USER_AMOUNT_REQUEST_SEND = "ADD_USER_AMOUNT_REQUEST_SEND";
export const ADD_USER_AMOUNT_REQUEST_SUCCESS =
  "ADD_USER_AMOUNT_REQUEST_SUCCESS";
export const ADD_USER_AMOUNT_REQUEST_FAIL = "ADD_USER_AMOUNT_REQUEST_FAIL";

export const REMOVE_USER_AMOUNT_REQUEST_SEND =
  "REMOVE_USER_AMOUNT_REQUEST_SEND";
export const REMOVE_USER_AMOUNT_REQUEST_SUCCESS =
  "REMOVE_USER_AMOUNT_REQUEST_SUCCESS";
export const REMOVE_USER_AMOUNT_REQUEST_FAIL =
  "REMOVE_USER_AMOUNT_REQUEST_FAIL";

// APP WALLET

// PERCENTAGE SETTINGS

export const ADD_DELIVERY_FEE_REQUEST_SEND = "ADD_DELIVERY_FEE_REQUEST_SEND";
export const ADD_DELIVERY_FEE_REQUEST_SUCCESS =
  "ADD_DELIVERY_FEE_REQUEST_SUCCESS";
export const ADD_DELIVERY_FEE_REQUEST_FAIL = "ADD_DELIVERY_FEE_REQUEST_FAIL";

export const GET_PERCENTAGE_REQUEST_SEND = "GET_PERCENTAGE_REQUEST_SEND";
export const GET_PERCENTAGE_REQUEST_SUCCESS = "GET_PERCENTAGE_REQUEST_SUCCESS";
export const GET_PERCENTAGE_REQUEST_FAIL = "GET_PERCENTAGE_REQUEST_FAIL";

export const UPDATE_DELIVERY_CUT_REQUEST_SEND =
  "UPDATE_DELIVERY_CUT_REQUEST_SEND";
export const UPDATE_DELIVERY_CUT_REQUEST_SUCCESS =
  "UPDATE_DELIVERY_CUT_REQUEST_SUCCESS";
export const UPDATE_DELIVERY_CUT_REQUEST_FAIL =
  "UPDATE_DELIVERY_CUT_REQUEST_FAIL";

// SELLERS TRX

export const GET_SELLERS_TRX_REQUEST_SEND = "GET_SELLERS_TRX_REQUEST_SEND";
export const GET_SELLERS_TRX_REQUEST_SUCCESS =
  "GET_SELLERS_TRX_REQUEST_SUCCESS";
export const GET_SELLERS_TRX_REQUEST_FAIL = "GET_SELLERS_TRX_REQUEST_FAIL";

export const GET_SELLER_TRX_REQUEST_SEND = "GET_SELLER_TRX_REQUEST_SEND";
export const GET_SELLER_TRX_REQUEST_SUCCESS = "GET_SELLER_TRX_REQUEST_SUCCESS";
export const GET_SELLER_TRX_REQUEST_FAIL = "GET_SELLER_TRX_REQUEST_FAIL";

export const GET_SHOP_TRX_REQUEST_SEND = "GET_SHOP_TRX_REQUEST_SEND";
export const GET_SHOP_TRX_REQUEST_SUCCESS = "GET_SHOP_TRX_REQUEST_SUCCESS";
export const GET_SHOP_TRX_REQUEST_FAIL = "GET_SHOP_TRX_REQUEST_FAIL";

export const SHOP_MAKE_PAYMENT_REQUEST_SEND = "SHOP_MAKE_PAYMENT_REQUEST_SEND";
export const SHOP_MAKE_PAYMENT_REQUEST_SUCCESS =
  "SHOP_MAKE_PAYMENT_REQUEST_SUCCESS";
export const SHOP_MAKE_PAYMENT_REQUEST_FAIL = "SHOP_MAKE_PAYMENT_REQUEST_FAIL";

export const SHOP_CREDIT_UPDATE_REQUEST_SEND =
  "SHOP_CREDIT_UPDATE_REQUEST_SEND";
export const SHOP_CREDIT_UPDATE_REQUEST_SUCCESS =
  "SHOP_CREDIT_UPDATE_REQUEST_SUCCESS";
export const SHOP_CREDIT_UPDATE_REQUEST_FAIL =
  "SHOP_CREDIT_UPDATE_REQUEST_FAIL";

export const SHOP_ADJUST_CASH_REQUEST_SEND = "SHOP_ADJUST_CASH_REQUEST_SEND";
export const SHOP_ADJUST_CASH_REQUEST_SUCCESS =
  "SHOP_ADJUST_CASH_REQUEST_SUCCESS";
export const SHOP_ADJUST_CASH_REQUEST_FAIL = "SHOP_ADJUST_CASH_REQUEST_FAIL";

export const SELLER_TRX_START_DATE = "SELLER_TRX_START_DATE";
export const SELLER_TRX_END_DATE = "SELLER_TRX_END_DATE";
export const SHOPS_TRX_START_DATE = "SHOPS_TRX_START_DATE";
export const SHOPS_TRX_END_DATE = "SHOPS_TRX_END_DATE";
export const SHOP_TRX_START_DATE = "SHOP_TRX_START_DATE";
export const SHOP_TRX_END_DATE = "SHOP_TRX_END_DATE";
export const SELLER_WALLET_SEARCH_KEY = "SELLER_WALLET_SEARCH_KEY";
export const SHOP_WALLET_SEARCH_KEY = "SHOP_WALLET_SEARCH_KEY";
export const SHOP_WALLET_TYPE = "SHOP_WALLET_TYPE";
export const SHOP_WALLET_ORDER_BY = "SHOP_WALLET_ORDER_BY";
export const SHOP_WALLET_AMOUNT_RANGE = "SHOP_WALLET_AMOUNT_RANGE";
export const SHOP_WALLET_AMOUNT_RANGE_TYPE = "SHOP_WALLET_AMOUNT_RANGE_TYPE";
export const SHOP_WALLET_CREATED_BY = "SHOP_WALLET_CREATED_BY";

// DELIVERY MAN TRX

export const GET_DELIVERY_TRX_REQUEST_SEND = "GET_DELIVERY_TRX_REQUEST_SEND";
export const GET_DELIVERY_TRX_REQUEST_SUCCESS =
  "GET_DELIVERY_TRX_REQUEST_SUCCESS";
export const GET_DELIVERY_TRX_REQUEST_FAIL = "GET_DELIVERY_TRX_REQUEST_FAIL";

export const DELIVERY_TRX_START_DATE = "DELIVERY_TRX_START_DATE";
export const DELIVERY_TRX_END_DATE = "DELIVERY_TRX_END_DATE";

export const RIDER_MAKE_PAYMENT_REQUEST_SEND =
  "RIDER_MAKE_PAYMENT_REQUEST_SEND";
export const RIDER_MAKE_PAYMENT_REQUEST_SUCCESS =
  "RIDER_MAKE_PAYMENT_REQUEST_SUCCESS";
export const RIDER_MAKE_PAYMENT_REQUEST_FAIL =
  "RIDER_MAKE_PAYMENT_REQUEST_FAIL";

export const RIDER_RECEIVED_PAYMENT_REQUEST_SEND =
  "RIDER_MAKE_PAYMENT_REQUEST_SEND";
export const RIDER_RECEIVED_PAYMENT_REQUEST_SUCCESS =
  "RIDER_MAKE_PAYMENT_REQUEST_SUCCESS";
export const RIDER_RECEIVED_PAYMENT_REQUEST_FAIL =
  "RIDER_MAKE_PAYMENT_REQUEST_FAIL";

// DROP Transactions

export const GET_DROP_TRX_REQUEST_SEND = "GET_DROP_TRX_REQUEST_SEND";
export const GET_DROP_TRX_REQUEST_SUCCESS = "GET_DROP_TRX_REQUEST_SUCCESS";
export const GET_DROP_TRX_REQUEST_FAIL = "GET_DROP_TRX_REQUEST_FAIL";

export const DROP_TRX_START_DATE = "DROP_TRX_START_DATE";
export const DROP_TRX_END_DATE = "DROP_TRX_END_DATE";

export const GET_ALL_TRX_REQUEST_SEND = "GET_ALL_TRX_REQUEST_SEND";
export const GET_ALL_TRX_REQUEST_SUCCESS = "GET_ALL_TRX_REQUEST_SUCCESS";
export const GET_ALL_TRX_REQUEST_FAIL = "GET_ALL_TRX_REQUEST_FAIL";
export const UPDATE_TRX_SORT_BY = "UPDATE_TRX_SORT_BY";
export const UPDATE_TRX_SEARCH_KEY = "UPDATE_TRX_SEARCH_KEY";
export const UPDATE_TRX_ACCOUNT_TYPE = "UPDATE_TRX_ACCOUNT_TYPE";

// ORDER

export const ALL_ORDERS_REQUEST_SEND = "ALL_ORDERS_REQUEST_SEND";
export const ALL_ORDERS_REQUEST_SUCCESS = "ALL_ORDERS_REQUEST_SUCCESS";
export const ALL_ORDERS_REQUEST_FAIL = "ALL_ORDERS_RORDERS_REQUEST_FAIL";

export const SEND_ORDER_FLAG_REQUEST_SEND = "SEND_ORDER_FLAG_REQUEST_SEND";
export const SEND_ORDER_FLAG_REQUEST_SUCCESS =
  "SEND_ORDER_FLAG_REQUEST_SUCCESS";
export const SEND_ORDER_FLAG_REQUEST_FAIL =
  "SEND_ORDER_FLAG_RORDERS_REQUEST_FAIL";

export const DELETE_ORDER_FLAG_REQUEST_SEND = "DELETE_ORDER_FLAG_REQUEST_SEND";
export const DELETE_ORDER_FLAG_REQUEST_SUCCESS =
  "DELETE_ORDER_FLAG_REQUEST_SUCCESS";
export const DELETE_ORDER_FLAG_REQUEST_FAIL =
  "DELETE_ORDER_FLAG_RORDERS_REQUEST_FAIL";

export const CANCEL_ORDER_REQUEST_SEND = "CANCEL_ORDER_REQUEST_SEND";
export const CANCEL_ORDER_REQUEST_SUCCESS = "CANCEL_ORDER_REQUEST_SUCCESS";
export const CANCEL_ORDER_REQUEST_FAIL = "CANCEL_ORDER_ORDERS_REQUEST_FAIL";

export const UPDATE_ORDER_START_DATE_FILTER = "UPDATE_ORDER_START_DATE_FILTER";
export const UPDATE_ORDER_END_DATE_FILTER = "UPDATE_ORDER_END_DATE_FILTER";
export const UPDATE_ORDER_SORT_BY_FILTER = "UPDATE_ORDER_SORT_BY_FILTER";
export const UPDATE_ORDER_TYPE_FILTER = "UPDATE_ORDER_TYPE_FILTER";
export const UPDATE_ORDER_SEARCH_KEY = "UPDATE_ORDER_SEARCH_KEY";
export const UPDATE_ORDER_BY_SHOP_TYPE = "UPDATE_ORDER_BY_SHOP_TYPE";

export const ORDER_UPDATE_STATUS_REQUEST_SEND =
  "ORDER_UPDATE_STATUS_REQUEST_SEND";
export const ORDER_UPDATE_STATUS_REQUEST_SUCCESS =
  "ORDER_UPDATE_STATUS_REQUEST_SUCCESS";
export const ORDER_UPDATE_STATUS_REQUEST_FAIL =
  "ORDER_UPDATE_STATUS_REQUEST_FAIL";

export const ACTIVE_DELIVERY_MANS_REQUEST_SEND =
  "ACTIVE_DELIVERY_MANS_REQUEST_SEND";
export const ACTIVE_DELIVERY_MANS_REQUEST_SUCCESS =
  "ACTIVE_DELIVERY_MANS_REQUEST_SUCCESS";
export const ACTIVE_DELIVERY_MANS_REQUEST_FAIL =
  "ACTIVE_DELIVERY_MANS_REQUEST_FAIL";

// CHAT
export const UPDATE_CHAT_SORT_BY_FILTER = "UPDATE_CHAT_SORT_BY_FILTER";
export const UPDATE_CHAT_TYPE_FILTER = "UPDATE_CHAT_TYPE_FILTER";

export const ALL_CHAT_REQUEST_SEND = "ALL_CHAT_REQUEST_SEND";
export const ALL_CHAT_REQUEST_SUCCESS = "ALL_CHAT_REQUEST_SUCCESS";
export const ALL_CHAT_REQUEST_FAIL = "ALL_CHAT_REQUEST_FAIL";

export const ACCEPT_CHAT_REQUEST_SEND = "ACCEPT_CHAT_REQUEST_SEND";
export const ACCEPT_CHAT_REQUEST_SUCCESS = "ACCEPT_CHAT_REQUEST_SUCCESS";
export const ACCEPT_CHAT_REQUEST_FAIL = "ACCEPT_CHAT_RORDERS_REQUEST_FAIL";

export const REJECT_CHAT_REQUEST_SEND = "REJECT_CHAT_REQUEST_SEND";
export const REJECT_CHAT_REQUEST_SUCCESS = "REJECT_CHAT_REQUEST_SUCCESS";
export const REJECT_CHAT_REQUEST_FAIL = "REJECT_CHAT_RORDERS_REQUEST_FAIL";

export const SEND_MSG_TO_USER_REQUEST_SEND = "SEND_MSG_TO_USER_REQUEST_SEND";
export const SEND_MSG_TO_USER_REQUEST_SUCCESS =
  "SEND_MSG_TO_USER_REQUEST_SUCCESS";
export const SEND_MSG_TO_USER_REQUEST_FAIL = "SEND_MSG_TO_USER_REQUEST_FAIL";

export const CLOSE_CONVERSATION_REQUEST_SEND =
  "CLOSE_CONVERSATION_REQUEST_SEND";
export const CLOSE_CONVERSATION_REQUEST_SUCCESS =
  "CLOSE_CONVERSATION_REQUEST_SUCCESS";
export const CLOSE_CONVERSATION_REQUEST_FAIL =
  "CLOSE_CONVERSATION_REQUEST_FAIL";

// SOCKET

export const SOCKET_CONNECT_SEND = "SOCKET_CONNECT_SEND";
export const SOCKET_CONNECT_SUCCESS = "SOCKET_CONNECT_SUCCESS";
export const SOCKET_CONNECT_FAIL = "SOCKET_CONNECT_FAIL";

// CHANGE PASSWORD

export const CHANGE_PASSWORD_REQUEST_SEND = "CHANGE_PASSWORD_REQUEST_SEND";
export const CHANGE_PASSWORD_REQUEST_SUCCESS =
  "CHANGE_PASSWORD_REQUEST_SUCCESS";
export const CHANGE_PASSWORD_REQUEST_FAIL = "CHANGE_PASSWORD_REQUEST_FAIL";

// IMAGE UPLOAD

export const IMAGE_UPLOAD_REQUEST_SEND = "IMAGE_UPLOAD_REQUEST_SEND";
export const IMAGE_UPLOAD_REQUEST_SUCCESS = "IMAGE_UPLOAD_REQUEST_SUCCESS";
export const IMAGE_UPLOAD_REQUEST_FAIL = "IMAGE_UPLOAD_REQUEST_FAIL";

// NOTIFICATION

export const CREATE_NOTIFICATION_REQUEST_SEND =
  "CREATE_NOTIFICATION_REQUEST_SEND";
export const CREATE_NOTIFICATION_REQUEST_SUCCESS =
  "CREATE_NOTIFICATION_REQUEST_SUCCESS";
export const CREATE_NOTIFICATION_REQUEST_FAIL =
  "CREATE_NOTIFICATION_REQUEST_FAIL";

export const ALL_NOTIFICATIONS_REQUEST_SEND = "ALL_NOTIFICATIONS_REQUEST_SEND";
export const ALL_NOTIFICATIONS_REQUEST_SUCCESS =
  "ALL_NOTIFICATIONS_REQUEST_SUCCESS";
export const ALL_NOTIFICATIONS_REQUEST_FAIL = "ALL_NOTIFICATIONS_REQUEST_FAIL";

export const UPDATE_NOTIFICATION_STATUS_REQUEST_SEND =
  "UPDATE_NOTIFICATION_STATUS_REQUEST_SEND";
export const UPDATE_NOTIFICATION_STATUS_REQUEST_SUCCESS =
  "UPDATE_NOTIFICATION_STATUS_REQUEST_SUCCESS";
export const UPDATE_NOTIFICATION_STATUS_REQUEST_FAIL =
  "UPDATE_NOTIFICATION_STATUS_REQUEST_FAIL";

export const UPDATE_NOTIFICATION_ACTIVE_STATUS =
  "UPDATE_NOTIFICATION_ACTIVE_STATUS";
export const UPDATE_NOTIFICATION_ACCOUNT_TYPE =
  "UPDATE_NOTIFICATION_ACCOUNT_TYPE";
export const UPDATE_NOTIFICATION_TYPE = "UPDATE_NOTIFICATION_TYPE";

// TERMS AND CONDITIONS

export const UPDATE_TERMS_CONDITION_REQUEST_SEND =
  "UPDATE_TERMS_CONDITION_REQUEST_SEND";
export const UPDATE_TERMS_CONDITION_REQUEST_SUCCESS =
  "UPDATE_TERMS_CONDITION_REQUEST_SUCCESS";
export const UPDATE_TERMS_CONDITION_REQUEST_FAIL =
  "UPDATE_TERMS_CONDITION_REQUEST_FAIL";

export const GET_TERMS_CONDITION_REQUEST_SEND =
  "UPDATE_TERMS_CONDITION_REQUEST_SEND";
export const GET_TERMS_CONDITION_REQUEST_SUCCESS =
  "UPDATE_TERMS_CONDITION_REQUEST_SUCCESS";
export const GET_TERMS_CONDITION_REQUEST_FAIL =
  "UPDATE_TERMS_CONDITION_REQUEST_FAIL";

// TAG

export const ADD_TAG_REQUEST_SEND = "ADD_TAG_REQUEST_SEND";
export const ADD_TAG_REQUEST_SUCCESS = "ADD_TAG_REQUEST_SUCCESS";
export const ADD_TAG_REQUEST_FAIL = "ADD_TAG_REQUEST_FAIL";

export const EDIT_TAG_REQUEST_SEND = "EDIT_TAG_REQUEST_SEND";
export const EDIT_TAG_REQUEST_SUCCESS = "EDIT_TAG_REQUEST_SUCCESS";
export const EDIT_TAG_REQUEST_FAIL = "EDIT_TAG_REQUEST_FAIL";

export const GET_TAGS_REQUEST_SEND = "GET_TAGS_REQUEST_SEND";
export const GET_TAGS_REQUEST_SUCCESS = "GET_TAGS_REQUEST_SUCCESS";
export const GET_TAGS_REQUEST_FAIL = "GET_TAGS_REQUEST_FAIL";

// FILTER KEY
export const UPDATE_ORDER_CHAT_SEARCH_KEY = "UPDATE_ORDER_CHAT_SEARCH_KEY";
export const UPDATE_SEARCH_KEY = "UPDATE_SEARCH_KEY";
export const UPDATE_DEFAULT_MESSAGE_SEARCH_KEY =
  "UPDATE_DEFAULT_MESSAGE_SEARCH_KEY";
export const UPDATE_PRODUCT_SEARCH_KEY = "UPDATE_PRODUCT_SEARCH_KEY";
export const UPDATE_TAG_SEARCH_KEY = "UPDATE_TAG_SEARCH_KEY";
export const UPDATE_SHOP_SEARCH_KEY = "UPDATE_SHOP_SEARCH_KEY";
export const UPDATE_RIDER_SEARCH_KEY = "UPDATE_RIDER_SEARCH_KEY";
export const UPDATE_STATUS_KEY = "UPDATE_STATUS_KEY";
export const UPDATE_SORT_BY_KEY = "UPDATE_SORT_BY_KEY";
export const UPDATE_TYPE_KEY = "UPDATE_TYPE_KEY";
export const UPDATE_CREATED_BY_KEY = "UPDATE_CREATED_BY_KEY";
export const UPDATE_CURRENT_STATUS_KEY = "UPDATE_CURRENT_STATUS_KEY";
export const SET_STATUS_FALSE = "SET_STATUS_FALSE";
export const UPDATE_PRODUCT_VISIBILITY_KEY = "UPDATE_PRODUCT_VISIBILITY_KEY";
export const UPDATE_SELLER_SUB_TYPE = "UPDATE_SELLER_SUB_TYPE";
export const UPDATE_SHOP_LIVE_STATUS = "UPDATE_SHOP_LIVE_STATUS";
export const UPDATE_START_DATE = "UPDATE_START_DATE";
export const UPDATE_END_DATE = "UPDATE_END_DATE";
export const UPDATE_DEAL_TYPE_KEY = "UPDATE_DEAL_TYPE_KEY";
export const UPDATE_DELIVERY_SORT_BY_KEY = "UPDATE_DELIVERY_SORT_BY_KEY";
export const UPDATE_DELIVERY_SEARCH_KEY = "UPDATE_DELIVERY_SEARCH_KEY";
export const UPDATE_SHOP_TRX_START_DATE = "UPDATE_SHOP_TRX_START_DATA";
export const UPDATE_SHOP_TRX_END_DATE = "UPDATE_SHOP_TRX_END_DATA";
export const UPDATE_ACTIVITY_START_DATE = "UPDATE_ACTIVITY_START_DATE";
export const UPDATE_ACTIVITY_END_DATE = "UPDATE_ACTIVITY_END_DATE";
export const RIDERS_TRX_START_DATE = "RIDERS_TRX_START_DATE";
export const RIDERS_TRX_END_DATE = "RIDERS_TRX_END_DATE";
export const RIDER_TRX_START_DATE = "RIDER_TRX_START_DATE";
export const RIDER_TRX_END_DATE = "RIDER_TRX_END_DATE";
export const RIDER_CASH_TRX_START_DATE = "RIDER_CASH_TRX_START_DATE";
export const RIDER_CASH_TRX_END_DATE = "RIDER_CASH_TRX_END_DATE";
export const UPDATE_PRODUCT_STATUS_KEY = "UPDATE_PRODUCT_STATUS_KEY";
export const UPDATE_RIDER_LIVE_STATUS = "UPDATE_RIDER_LIVE_STATUS";
export const UPDATE_DASHBOARD_CARD_START_DATE_FILTER =
  "UPDATE_DASHBOARD_CARD_START_DATE_FILTER";
export const UPDATE_DASHBOARD_CARD_END_DATE_FILTER =
  "UPDATE_DASHBOARD_CARD_END_DATE_FILTER";
export const UPDATE_LYXA_PAY_SEARCH_KEY = "UPDATE_LYXA_PAY_SEARCH_KEY";
export const UPDATE_PRODUCT_CATEGORY = "UPDATE_PRODUCT_CATEGORY";
