export const listData = [
  {
    id: 1,
    name: 'Free Delivery',
    bannerImage: '/broken.jpg',
    type: ['Deal', 'Tags'],
    status: 'active',
    date: 'Sep 9, 2020 7:15 PM',
  },
  {
    id: 2,
    name: 'Free Delivery',
    bannerImage: '/broken.jpg',
    type: ['Restaurant'],
    status: 'active',
    date: 'Sep 9, 2020 7:15 PM',
  },
  {
    id: 3,
    name: 'Buy 1, Get 1 Free',
    bannerImage: '/broken.jpg',
    type: ['Deal'],
    status: 'active',
    date: 'Sep 9, 2020 7:15 PM',
  },
  {
    id: 4,
    name: 'Free Delivery',
    bannerImage: '/broken.jpg',
    type: ['Deal', 'Tags'],
    status: 'active',
    date: 'Sep 9, 2020 7:15 PM',
  },
  {
    id: 5,
    name: 'Free Delivery',
    bannerImage: '/broken.jpg',
    type: ['Restaurant'],
    status: 'active',
    date: 'Sep 9, 2020 7:15 PM',
  },
];
