apiVersion: apps/v1
kind: Deployment
metadata:
  name: drop-admin
  namespace: default
  labels:
    app: drop-admin
spec:
  selector:
    matchLabels:
      app: drop-admin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 2 # number of pods
  template:
    metadata:
      labels:
        app: drop-admin
    spec:
      containers:
        - name: drop-admin
          image: gcr.io/for-poc-325210/drop-admin:v78
          imagePullPolicy: Always
          ports:
            - containerPort: 30038
              protocol: TCP
      imagePullSecrets:
        - name: dropimagepullkey
# docker build -t gcr.io/for-poc-325210/drop-admin:v50 .

# docker push gcr.io/for-poc-325210/drop-admin:v50

# kubectl apply -f k8s/deployment.yaml

# gcloud auth login
