export const rankedItems = [
  {
    _id: 1,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: true,
    sales: '640',
    price: '12',
  },

  {
    _id: 2,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: false,
    sales: '640',
    price: '12',
  },
  {
    _id: 3,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: false,
    price: '12',
    sales: '640',
  },

  {
    _id: 33,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: false,
    price: '12',
    sales: '640',
  },
  {
    _id: 4,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: true,
    price: '12',
    sales: '640',
  },
  {
    _id: 5,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: true,
    price: '12',
    sales: '640',
  },
  {
    _id: 6,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: true,
    price: '12',
    sales: '640',
  },
  {
    _id: 7,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: true,
    price: '12',
    sales: '640',
  },
  {
    _id: 8,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: false,
    price: '12',
    sales: '640',
  },
  {
    _id: 9,
    name: 'Sandwich Falafel',
    sold: 64,
    isIncreased: true,
    price: '12',
    sales: '640',
  },
];
